on:
  push:
    branches:
      - main
    paths-ignore:
      - 'kustomize/**'

name: Build EMS-Items docker image

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}   # checkout the correct branch name
        fetch-depth: 0                # fetch the whole repo history
     # Generate previous and next version from git tags
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.11
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.11
      with:
        useConfigFile: true
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ems-items
        IMAGE_TAG: ${{ steps.gitversion.outputs.majorMinorPatch }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -f ./src/WebUI/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --target "final" .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Modify version number
      uses: mingjun97/file-regex-replace@v1
      with:
        regex: '(image: .*:)(.*)'
        replacement: '$1${{ steps.gitversion.outputs.majorMinorPatch }}'
        include: 'deployment.yaml'    # Optional, defaults to ".*"
        path: 'kustomize'

    - name: Show deployment
      run: cat kustomize/deployment.yaml

    - name: Update deployment
      uses: test-room-7/action-update-file@v1
      with:
          file-path: kustomize/deployment.yaml
          commit-msg: 'Update deployment to v${{ steps.gitversion.outputs.majorMinorPatch }}'
          github-token: ${{ secrets.GITHUB_TOKEN }}